In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
train_df = pd.read_csv("./train_data_1120.csv")
test_df = pd.read_csv("./test_data_1120.csv")

In [3]:
train_df[['poi_id','uuid']].head()

   poi_id    uuid
0   31554  351320
1   11426  351321
2     135  351322
3   21332  351323
4       1  351324

In [3]:
user_feature = ['uuid','age','gender','job']
poi_feature = ['poi_id','poi_avg_discount','avg_price','poi_star','cate_level1','cate_level2','cate_level3']
poi_uu_df = pd.concat([train_df[['poi_id','uuid']],test_df[['poi_id','uuid']]])
poi_df = pd.concat([train_df[poi_feature],test_df[poi_feature]])
uu_df = pd.concat([train_df[user_feature],test_df[user_feature]])

In [60]:
uu_df.head()

     uuid       age  gender  job
0  351320  0.000000       0    0
1  351321  0.000000       0    1
2  351322 -1.384194       1    1
3  351323 -1.728051       0    2
4  351324  0.507021       0    0

In [5]:
#figure out the center user&poi
poi_df_c = poi_df.iloc[:,0:6]
uu_df_c = uu_df.iloc[:,0:3]

In [6]:
poi_df_c.shape

(4398064, 7)

In [7]:
poi_df_c.drop_duplicates(subset='poi_id',keep='first', inplace=True)

In [6]:
uu_df_c.drop_duplicates(subset='uuid',keep='first', inplace=True)

In [8]:
poi_df_c=poi_df_c.append(poi_df_c.mean(),ignore_index=True)

In [9]:
poi_df_c

,poi_id,poi_avg_discount,avg_price,poi_star,cate_level1,cate_level2,cate_level3
0,31554.0,3.257822e-01,-0.051390,-0.193580,0.000000,0.000000,47.000000
1,11426.0,7.973092e-01,-0.110390,-1.070293,0.000000,0.000000,16.000000
2,135.0,2.870163e-01,-0.110390,0.537015,0.000000,1.000000,0.000000
3,21332.0,-1.136608e+00,0.066609,-0.778056,0.000000,17.000000,123.000000
4,1.0,-1.453344e+00,0.090903,0.829253,0.000000,20.000000,54.000000
5,5245.0,-9.742556e-15,0.146432,-1.216412,0.000000,3.000000,17.000000
6,5813.0,-9.416126e-02,-0.211036,-0.047461,0.000000,3.000000,83.000000
7,18840.0,1.334457e-01,-0.013214,0.244777,0.000000,2.000000,9.000000
8,10713.0,7.128402e-01,0.014551,-0.047461,0.000000,2.000000,9.000000
9,1082.0,7.167039e-01,-0.186742,0.829253,0.000000,3.000000,57.000000
10,1821.0,7.754376e-01,0.118668,0.829253,0.000000,0.000000,43.000000
11,16812.0,6.033275e-01,-0.158978,-0.047461,0.000000,6.000000,2.000000
12,10614.0,1.748655e+00,-0.040978,-0.339699,0.000000,2.000000,11.000000
13,3428.0,4.165003e-01,-0.058331,-0.339699,0.000000,0.000000,40.000000
14,191.0,-3.438771e-01,-0.211036,0.829253,0.000000,1.000000,0.000000
15,601.0,-1.009115e-01,-0.217978,-0.047461,0.000000,7.000000,7.000000
16,16941.0,7.652022e-02,-0.079155,-0.485818,0.000000,2.000000,11.000000
17,7613.0,4.958423e-01,-0.068743,0.829253,0.000000,4.000000,6.000000
18,31183.0,-5.472540e-01,-0.002802,-2.093126,0.000000,0.000000,3.000000
19,13147.0,-2.210768e+00,1.350720,-0.924174,0.000000,4.000000,6.000000
20,11714.0,-9.582325e-01,0.052727,0.829253,0.000000,1.000000,0.000000
21,13288.0,7.790074e-01,-0.044449,-0.339699,0.000000,5.000000,42.000000
22,9141.0,5.173897e-01,-0.044449,0.098658,0.000000,0.000000,3.000000
23,910.0,-6.244881e-01,0.149903,0.829253,0.000000,0.000000,4.000000
24,1772.0,1.135539e+00,0.070080,0.829253,0.000000,4.000000,27.000000
25,18691.0,-9.953645e-02,-0.152037,-1.362531,0.000000,9.000000,39.000000
26,1883.0,7.437742e-01,0.108256,0.683134,0.000000,4.000000,21.000000
27,14507.0,-9.742556e-15,0.139491,0.098658,0.000000,2.000000,9.000000
28,1950.0,-9.612602e-02,-0.207566,0.390896,0.000000,1.000000,0.000000
29,3640.0,-9.742556e-15,0.066609,0.098658,0.000000,0.000000,16.000000
...,...,...,...,...,...,...,...
40089,40089.0,1.573148e+00,0.014551,0.829253,0.000000,9.000000,30.000000
40090,40090.0,-9.742556e-15,0.118668,-0.631937,0.000000,2.000000,11.000000
40091,40091.0,-9.742556e-15,0.559430,0.829253,0.000000,12.000000,44.000000
40092,40092.0,-9.416126e-02,0.038845,-0.047461,0.000000,0.000000,75.000000
40093,40093.0,-8.820913e-01,0.163785,0.537015,2.000000,40.000000,251.000000
40094,40094.0,-8.813278e-01,0.063139,-0.193580,0.000000,7.000000,26.000000
40095,40095.0,-7.661853e-01,0.254020,0.829253,2.000000,40.000000,251.000000
40096,40096.0,-8.470989e-02,0.611489,0.829253,2.000000,48.000000,271.000000
40097,40097.0,2.187420e+00,0.313020,0.098658,0.000000,4.000000,6.000000
40098,40098.0,-6.246985e-01,-0.197154,-0.631937,0.000000,3.000000,19.000000
40099,40099.0,1.932492e+00,0.153373,0.829253,2.000000,40.000000,251.000000
40100,40100.0,5.955669e-01,0.066609,-0.631937,0.000000,10.000000,96.000000
40101,40101.0,-6.805660e-01,0.219314,-0.047461,2.000000,40.000000,251.000000
40102,40102.0,-4.297647e-01,-0.068743,0.244777,2.000000,45.000000,266.000000
40103,40103.0,-2.837279e+00,0.004139,0.390896,2.000000,43.000000,264.000000
40104,40104.0,1.065055e+00,0.365078,0.829253,0.000000,4.000000,6.000000
40105,40105.0,8.562936e-01,0.153373,-0.047461,2.000000,40.000000,251.000000
40106,40106.0,1.222136e+00,-0.110390,-1.070293,0.000000,3.000000,126.000000
40107,40107.0,-9.742556e-15,0.354666,0.098658,0.000000,4.000000,6.000000
40108,40108.0,1.322410e+00,-0.068743,-0.047461,0.000000,0.000000,3.000000
40109,40109.0,-9.742556e-15,-0.082625,-2.093126,0.000000,6.000000,2.000000
40110,40110.0,5.079707e-02,0.111727,0.098658,2.000000,40.000000,251.000000
40111,40111.0,-1.705740e+00,-0.145096,-2.093126,0.000000,1.000000,0.000000
40112,40112.0,1.867053e+00,0.149903,0.829253,2.000000,40.000000,251.000000
40113,40113.0,-9.742556e-15,-0.093037,-0.631937,0.000000,7.000000,26.000000
40114,40114.0,-9.742556e-15,-0.047920,0.098658,0.000000,3.000000,19.000000
40115,40115.0,-1.914467e+00,-0.158978,-1.362531,0.000000,1.000000,0.000000
40116,40116.0,-9.627456e-01,-0.093037,0.829253,0.000000,0.000000,172.000000
40117,40117.0,1.171759e+00,-0.224919,-1.362531,0.000000,7.000000,7.000000
40118,20058.5,1.413002e-02,0.032013,-0.122595,0.009796,5.010693,30.943267

In [23]:
uu_df_c=uu_df_c.append(uu_df_c.mean(),ignore_index=True)

              uuid       age    gender       job
0         351320.0  0.000000  0.000000  0.000000
1         351321.0  0.000000  0.000000  1.000000
2         351322.0 -1.384194  1.000000  1.000000
3         351323.0 -1.728051  0.000000  2.000000
4         351324.0  0.507021  0.000000  0.000000
5         351325.0  0.000000  0.000000  1.000000
6          46593.0  0.000000  0.000000  0.000000
7         351326.0  0.000000  0.000000  1.000000
8         351327.0 -1.212265  0.000000  2.000000
9          46594.0 -1.040337  1.000000  0.000000
10        351328.0 -0.524551  1.000000  0.000000
11        351329.0  0.000000  1.000000  2.000000
12         46595.0 -0.868408  1.000000  1.000000
13        351330.0  0.000000  1.000000  0.000000
14        351331.0  0.000000  1.000000  1.000000
15        351332.0  0.000000  1.000000  1.000000
16        351333.0  1.710521  0.000000  0.000000
17        351334.0 -0.524551  1.000000  0.000000
18        351335.0 -1.384194  0.000000  0.000000
19        351336.0  0.000000  0.000000  0.000000
20        351337.0 -0.696479  0.000000  0.000000
21         46596.0 -0.868408  1.000000  2.000000
22         46597.0  0.000000  0.000000  0.000000
23        351338.0 -0.008765  0.000000  1.000000
24        351339.0 -0.696479  1.000000  0.000000
25        351340.0 -0.524551  1.000000  0.000000
26        351341.0 -0.696479  1.000000  0.000000
27        351342.0  1.710521  1.000000  0.000000
28        351343.0 -0.868408  1.000000  1.000000
29        351344.0  0.000000  0.000000  1.000000
...            ...       ...       ...       ...
3795792  3795792.0 -0.524551  1.000000  0.000000
3795793  3795793.0  0.000000  0.000000  1.000000
3795794  3795794.0  0.000000  0.000000  0.000000
3795795  3795795.0  0.000000  0.000000  1.000000
3795796  3795796.0 -1.899980  0.000000  2.000000
3795797  3795797.0 -1.384194  0.000000  1.000000
3795798  3795798.0 -0.696479  1.000000  0.000000
3795799  3795799.0  1.538592  0.000000  0.000000
3795800  3795800.0 -0.524551  0.000000  0.000000
3795801  3795801.0  0.000000  0.000000  1.000000
3795802  3795802.0 -0.180694  0.000000  0.000000
3795803  3795803.0  0.000000  0.000000  2.000000
3795804  3795804.0  1.882450  1.000000  1.000000
3795805  3795805.0 -0.180694  1.000000  0.000000
3795806  3795806.0 -2.071908  0.000000  2.000000
3795807  3795807.0  0.000000  0.000000  1.000000
3795808  3795808.0 -0.180694  1.000000  0.000000
3795809  3795809.0  0.335092  0.000000  0.000000
3795810  3795810.0 -0.524551  0.000000  0.000000
3795811  3795811.0  0.000000  1.000000  0.000000
3795812  3795812.0 -0.696479  0.000000  1.000000
3795813  3795813.0  0.000000  1.000000  1.000000
3795814  3795814.0 -0.868408  0.000000  0.000000
3795815  3795815.0 -0.696479  1.000000  0.000000
3795816  3795816.0  0.000000  1.000000  1.000000
3795817  3795817.0 -0.696479  1.000000  0.000000
3795818  3795818.0 -1.212265  0.000000  2.000000
3795819  3795819.0 -0.524551  0.000000  0.000000
3795820  3795820.0 -1.556123  1.000000  2.000000
3795821  1897910.0  0.003617  0.365246  0.768073

[3795822 rows x 4 columns]

In [28]:
def cos_sim(vector_a, vector_b):
    """
    计算两个向量之间的余弦相似度
    :param vector_a: 向量 a 
    :param vector_b: 向量 b
    :return: sim
    """
    vector_a = np.mat(vector_a)
    vector_b = np.mat(vector_b)
    num = float(vector_a * vector_b.T)
    denom = np.linalg.norm(vector_a) * np.linalg.norm(vector_b)
    cos = num / denom
    sim = 0.5 + 0.5 * cos
    return sim

In [25]:
poiid = np.array(train_df['poi_id'])
poi_vec = {}
poiid_part = np.array(poi_df_c['poi_id'])
poi_vec_set = poi_df_c.iloc[:,1:]
poi_vec_list = np.array(poi_vec_set)
poi_mat = cosine_similarity(poi_vec_list)
poi_mat = poi_mat[-1,:] #选出center的

In [17]:
len(poi_mat)

40119

In [27]:
uu_center_vec = np.array(uu_df_c.iloc[-1,1:])
print(uu_center_vec)

[0. 0. 0.]

In [13]:
uuid = np.array(train_df['uuid'])
uu_vec = {}
uu_sim = []
uuid_part = np.array(uu_df_c['uuid'])
uu_vec_set = uu_df_c.iloc[:,1:]
uu_center_vec = np.array(uu_df_c.iloc[-1,1:])
uu_vec_list = np.array(uu_vec_set)
for i in range(len(uuid)):
    uu_vec[uuid[i]] = uu_vec_list[i]
    tmp_sim = cos_sim(uu_vec_list[i],uu_center_vec)
for i in range(len(uuid)):

SyntaxError: unexpected EOF while parsing (<ipython-input-13-15e7e511021d>, line 13)

In [10]:
uuid[0]

351320

In [41]:
poi_vec[20058]

0.42915462866068055

In [27]:
poi_dist_part = {}
for i in range(len(poiid_part)):
    poi_dist_part[poiid_part[i]] = poi_mat[i]
poi_dist_all = []
for i in range(len(poiid)):
    poi_dist_all.append(poi_dist_part[poiid[i]])

In [19]:
len(poi_dist_all)

192000

In [28]:
#test_df["poi_center_distance"] = poi_dist_all
train_df["poi_center_distance"] = poi_dist_all

In [22]:
test_df.describe()

,Unnamed: 0,poi_id,request_id,uuid,request_cate_id,device_type,gender,job,cate_level1,cate_level2,...,age,avg_price,poi_star,longitude_poi,latitude_poi,distance,poi_cnt_deal,poi_avg_discount,request_time_second,poi_center_distance
count,192000.00000,192000.000000,192000.0,1.920000e+05,192000.000000,192000.000000,192000.000000,192000.000000,192000.000000,192000.000000,...,192000.000000,192000.000000,192000.000000,192000.000000,192000.000000,192000.000000,192000.000000,192000.000000,192000.000000,192000.000000
mean,95999.50000,10056.349339,0.0,1.698374e+05,0.391969,0.429240,0.385542,0.749849,0.001510,4.568849,...,-0.124056,-0.001889,0.006912,0.023442,-0.013701,-0.014865,-0.033422,-0.010976,-0.106777,0.818713
std,55425.77018,9554.108743,0.0,6.508098e+05,2.219030,0.569535,0.486724,0.834413,0.059405,5.662705,...,0.967966,0.856547,0.946705,0.986032,1.014795,1.112981,0.982400,1.018517,0.968397,0.300939
min,0.00000,0.000000,0.0,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-2.243837,-0.280448,-6.476694,-5.513679,-2.176904,-0.154723,-0.826322,-5.958360,-3.637589,0.008019
25%,47999.75000,2114.000000,0.0,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.696479,-0.124272,-0.631937,-0.255585,-0.792815,-0.147065,-0.518994,-0.650672,-0.827845,0.812370
50%,95999.50000,6993.000000,0.0,0.000000e+00,0.000000,0.000000,0.000000,1.000000,0.000000,2.000000,...,-0.124056,-0.044449,0.244777,0.025628,-0.090159,-0.136289,-0.365330,-0.009624,0.016246,0.977659
75%,143999.25000,15639.000000,0.0,0.000000e+00,0.000000,1.000000,1.000000,1.000000,0.000000,7.000000,...,-0.008765,0.028433,0.829253,0.741213,0.727669,-0.104852,-0.058002,0.682532,0.617631,0.990993
max,191999.00000,40117.000000,0.0,3.795807e+06,64.000000,10.000000,1.000000,3.000000,5.000000,50.000000,...,6.868379,67.100666,0.829253,2.449850,2.839040,99.986695,3.629933,2.626186,2.034090,0.999993

In [ ]:
#test_df.drop(df.tail(n).index) 从尾部去掉 n 行

In [5]:
uu_df.drop_duplicates(keep='first', inplace=True)

In [7]:
uu_df.shape

(3800910, 2)

In [30]:
train_df.describe()

,Unnamed: 0,poi_id,request_id,uuid,request_cate_id,device_type,gender,job,cate_level1,cate_level2,...,avg_price,poi_star,longitude_poi,latitude_poi,distance,poi_cnt_deal,poi_avg_discount,request_time_second,action,poi_center_distance
count,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06,...,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06,4.206064e+06
mean,2.103032e+06,8.604995e+03,2.073333e+06,1.727734e+06,4.168864e-01,4.265223e-01,3.637027e-01,7.629803e-01,9.750208e-04,4.574542e+00,...,-1.518339e-15,-6.702805e-14,5.644342e-15,-4.130340e-15,1.294162e-15,-1.287428e-14,-9.159832e-15,7.775192e-17,2.366464e-02,8.057134e-01
std,1.214186e+06,8.138069e+03,1.213825e+06,1.163051e+06,2.294269e+00,5.729704e-01,4.810646e-01,8.413821e-01,4.162901e-02,5.602625e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.520021e-01,3.128131e-01
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,-2.804478e-01,-6.476694e+00,-1.613778e+01,-4.883440e+00,-1.547230e-01,-8.263219e-01,-5.958360e+00,-3.637852e+00,0.000000e+00,8.019086e-03
25%,1.051516e+06,1.964000e+03,1.021606e+06,6.412728e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,-1.381545e-01,-6.319366e-01,-3.848506e-01,-6.402088e-01,-1.468504e-01,-5.189940e-01,-6.243734e-01,-7.738156e-01,0.000000e+00,8.075576e-01
50%,2.103032e+06,6.062000e+03,2.073122e+06,1.692788e+06,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,2.000000e+00,...,-4.791963e-02,2.447770e-01,2.856504e-02,-8.644450e-02,-1.358276e-01,-3.653301e-01,-9.742556e-15,1.964221e-01,0.000000e+00,9.756609e-01
75%,3.154547e+06,1.318900e+04,3.124637e+06,2.744304e+06,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,7.000000e+00,...,2.843290e-02,8.292527e-01,7.436913e-01,7.029148e-01,-1.008865e-01,-5.800218e-02,6.739296e-01,7.248370e-01,0.000000e+00,9.909601e-01
max,4.206063e+06,4.011700e+04,4.176153e+06,3.795820e+06,6.400000e+01,1.500000e+01,1.000000e+00,3.000000e+00,5.000000e+00,5.200000e+01,...,3.792368e+02,8.292527e-01,2.449850e+00,3.102450e+00,1.048027e+02,3.629933e+00,2.626186e+00,2.034156e+00,1.000000e+00,9.999977e-01

In [31]:
train_df.to_csv('./train_data_1126.csv')
#test_df.to_csv('./test_data_1126.csv')

In [6]:
poi_df.drop_duplicates(subset='poi_id',keep='first', inplace=True)

In [10]:
poi_df.shape

(40118, 10)

In [7]:
dup=poi_uu_df[poi_uu_df.duplicated()].count()

In [8]:
poi_uu_visited = poi_uu_df.groupby(poi_uu_df.columns.tolist(),as_index=False).size()

In [9]:
poi_uu_visited.head()

poi_id  uuid
0       0       1744
        28         3
        84         1
        196        1
        297        1
dtype: int64

In [ ]:
poi_uu_visited =

In [7]:
poi_uu_visited.to_csv('input.edgelist', sep=' ', index=True)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.

In [8]:
poi_uu_visited.shape

(4233199,)

In [10]:
poi_vec_set = poi_df.iloc[:,1:]

In [11]:
poi_vec_list = np.array(poi_vec_set)

In [12]:
poiid = np.array(poi_df['poi_id'])

In [13]:
poiid[251]

18361

In [15]:
poi_vec_list.shape

(40118, 9)

In [16]:
poi_vec_list[250]

array([-3.36058537e-01, -6.72657995e-01,  1.45506234e-02, -1.07029343e+00,
        9.00085242e-01, -7.94110832e-02,  0.00000000e+00,  1.10000000e+01,
        3.80000000e+01])

In [14]:
def cos_sim(vector_a, vector_b):
    """
    计算两个向量之间的余弦相似度
    :param vector_a: 向量 a 
    :param vector_b: 向量 b
    :return: sim
    """
    vector_a = np.mat(vector_a)
    vector_b = np.mat(vector_b)
    num = float(vector_a * vector_b.T)
    denom = np.linalg.norm(vector_a) * np.linalg.norm(vector_b)
    cos = num / denom
    sim = 0.5 + 0.5 * cos
    return sim

In [72]:
#Figure the cos distance of each POI to put into the LINE
poi_sim = []
for i in range(len(poi_vec_list)):
    j = i
    while j < len(poi_vec_list):
        tmp_dis = cos_sim(poi_vec_list[i],poi_vec_list[j])
        poi_sim.append(poiid[i]+' '+poiid[j]+' '+tmp_dis+'\n')

0.9714045207910318

In [31]:
poiid[250:255]

250    21928
252    18361
253    11526
254    23803
255     9463
Name: poi_id, dtype: int64

In [35]:
poi_mat[251][1]

0.7865637610130763

In [15]:
poi_mat = cosine_similarity(poi_vec_list)

In [ ]:
poi_sim = []
for i in range(len(poi_vec_list)):
    j = i
    while j < len(poi_vec_list):
        poi_sim.append(str(poiid[i])+' '+str(poiid[j])+' '+str(poi_mat[i][j])+'\n')
        j = j + 1

In [44]:
len(poi_sim)

35092549

In [ ]:
with open('./input_poi.txt','w')as f:
    f.writelines(poi_sim)